const la_fiche_de_revision_du_theme_la_culture = {
  theme: "la culture",
  niveau: "c1",
  typing:[
    "vocabulaire",
    "les arts visuels",
    "la peinture",
    "un tableau",
    "un peintre célèbre",
    "une toile",
    "un chevalet",
    "une galerie d'art",
    "la sculpture",
    "une statue",
    "un sculpteur célèbre",
    "une œuvre d'art",
    "une exposition",
    "la photographie",
    "un photographe célèbre",
    "une photo",
    "un appareil photo",
    "un tirage",
    "la littérature",
    "les genres littéraires",
    "le roman",
    "la poésie",
    "le théâtre",
    "la nouvelle",
    "l'essai",
    "les écrivains célèbres",
    "victor hugo",
    "gustave flaubert",
    "albert camus",
    "simone de beauvoir",
    "jean-paul sartre",
    "les prix littéraires",
    "le prix goncourt",
    "le prix renaudot",
    "le prix nobel de littérature",
    "la musique",
    "les genres musicaux",
    "le jazz",
    "le rock",
    "la pop",
    "la musique classique",
    "le rap",
    "les instruments de musique",
    "la guitare",
    "le piano",
    "la batterie",
    "la flûte",
    "le violon",
    "les musiciens célèbres",
    "mozart",
    "beethoven",
    "freddie mercury",
    "elvis presley",
    "bob dylan",
    "expressions_courantes",
    "parler de ses goûts culturels",
    "j'aime beaucoup la peinture de monet.",
    "je suis fan de la musique de queen.",
    "je suis passionné(e) de littérature contemporaine.",
    "je suis fasciné(e) par l'histoire de l'art.",
    "parler de l'actualité culturelle",
    "as-tu vu la nouvelle exposition à la galerie d'art ?",
    "connais-tu le dernier roman de michel houellebecq ?",
    "est-ce que tu vas au concert de beyoncé ce soir ?",
    "on parle beaucoup du film \"parasite\" en ce moment.",
    "structures_grammaticales",
    "le subjonctif après \"il est important/essentiel que\"",
    "il est important que nous soyons attentifs à l'histoire de l'art.",
    "il est essentiel que les jeunes lisent plus de littérature.",
    "il est primordial que nous soutenions les artistes locaux.",
    "les adjectifs pour décrire les œuvres d'art",
    "ce tableau est sublime/magnifique/époustouflant.",
    "cette sculpture est étonnante/impressionnante/majestueuse.",
    "cette photo est intrigante/poignante/émouvante.",
    "exemples_textes",
    "\"les misérables\" de victor hugo",
    "\"l'étranger\" d'albert camus",
    "\"la joconde\" de léonard de vinci",
    "\"la guernica\" de pablo picasso",
    "\"la neuvième symphonie\" de ludwig van beethoven"
  ]
}
